spring:
  application:
    name: notiApiServer

  datasource:
    url: jdbc:mariadb://localhost:3306/x?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      pool-name: SpringBootJPAHikariCP

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: record

logging:
  level:
    org.springframework.data.jpa.domain.support.AuditingEntityListener: DEBUG

server:
  port: 8081